### PR TITLE
build: update tsconfig.json

### PR DESCRIPTION
**Pull request by himself65**

### CODE REVIEW

**Comment by Jack-Works** [comment]
@Himself65 hi did you formatted with prettier?

**Comment by himself65** [comment]
I use eslint standard rules in this repo

**Comment by Jack-Works** [comment]
> I use eslint standard rules in this repo

I prefer prettier than eslint style rules because prettier ones are much more restricted so we can save time on the styling.

**Comment by Jack-Works** [comment]
can u rebase and format this?

**Pull request closed without merging**
